// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL0NTP14SL-ZPtFXxfrdgBDhLTRvxlPms',
    appId: '1:780157077799:web:f5d2b4a5765ac1217b8102',
    messagingSenderId: '780157077799',
    projectId: 'chat-app-28733',
    authDomain: 'chat-app-28733.firebaseapp.com',
    storageBucket: 'chat-app-28733.appspot.com',
    measurementId: 'G-3QM05HF1L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_l1pq7NGTw61Y6H0BviGCm60MKN8Sl90',
    appId: '1:780157077799:android:6443d2bc514c68a67b8102',
    messagingSenderId: '780157077799',
    projectId: 'chat-app-28733',
    storageBucket: 'chat-app-28733.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6y6tt2k_JI1R7_qzY0W374-BO-0bWOaM',
    appId: '1:780157077799:ios:bdbc71914944e4937b8102',
    messagingSenderId: '780157077799',
    projectId: 'chat-app-28733',
    storageBucket: 'chat-app-28733.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6y6tt2k_JI1R7_qzY0W374-BO-0bWOaM',
    appId: '1:780157077799:ios:301841e27aaf8c737b8102',
    messagingSenderId: '780157077799',
    projectId: 'chat-app-28733',
    storageBucket: 'chat-app-28733.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
